# Generated by Django 5.1.6 on 2025-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='property_images/default.jpg', upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
