# Generated by Django 5.1.7 on 2025-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
