# Generated by Django 5.1.7 on 2025-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=10),
        ),
    ]
