# Generated by Django 5.1.7 on 2025-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_booking_agreement_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=255),
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
