# Generated by Django 5.1.6 on 2025-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_payment_status_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
